# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9043978ee9d06f71b915d1eb1bd7e00cca2bd3af2f8c5b6f1b9421c5e5cfd7aff8af3a3bf7ae91071eb0b9641b304b8a37b6812f337fe1e7a88fe5cccf729b8b

test:
  secret_key_base: c6fb8f8448734a37f9945742f8e2459ea72e1b5cfd0ab8c01d54b89ec1c4fe020456cc1078bed8559647e6c409d234e5082a1e2671552399179c967a7e418a12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
