# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b7cb85c44267b1907430ff533825a1d71081aa7c671954f150a9a84306000d06d508da5a9337f9fa7a427e114e8bde633444b0a8327f161c99bad8059e92ff7

test:
  secret_key_base: 68909f981b3e63df915d73f9d1469c2a9c038f0fe375ff5dcc6d6a5b4961c20a7a33f643e30dfdc20987024e4cbe1463c84b8d6168f72829b9c6edc87bbd9123

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
